### ISSUE TITLE
arrow navigation while editing cell content

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/spreadsheet#246]
**Originally by @alvarezguille**

---

Arrow keys should:
- if at the end of the value and right is pressed, it should select the cell to the right

Created after splitting #17464 since points 1, 3 and 4 were fixed but point 2 still needs to be fixed.

---

 Imported from https://dev.vaadin.com/ issue #17727

**Comment by ianscriven** [comment]
Is there any intention to fix this bug?

**Comment by johannesh2** [comment]
If I understood correctly this bug is invalid as we don't want to move out the cell when editing a value with clicking or F2, but only when entering a new value like in #598 . What do you think?

**Comment by ianscriven** [comment]
Agree - when you enter a cell by double-clicking or pressing F2, the arrow keys shouldn't make you leave the cell. But when you enter a new value after selecting a cell via single-clicking or using the arrow keys, then enter a value by typing, using the arrow keys again should save that new value and move to the appropriate adjacent skill. Users expect this behavior as it's what Excel does.

I don't think it's clear whether issue (or #235) refers to the edit value case or to the new value case. #598 might be a duplicate, depending on the intent of this issue.

**Comment by vlukashov** [comment]
Fixed in the PR #601.
We aim at releasing a fix for this issue in the next maintenance release of Vaadin Spreadsheet.
