### ISSUE TITLE
Column overflow is broken

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/spreadsheet#259]
**Originally by _lapocioni_**

---

Related to #17601 (ticket).

Loading the attached file into the Spreadsheet to verify the #17601 fix, the far right column has content values correctly aligned into the proper cells; the header (Total), instead, has the value into the proper cell, but is rendered on the right.

---

 Imported from https://dev.vaadin.com/ issue #18151

**Comment by WoozyG** [comment]
Uploading the attachment to https://demo.vaadin.com/spreadsheet/ displays the workbook just like Excel 2016, so I think this issue can be closed.  I checked because it would affect my users if it was still there :)

**Comment by alvarezguille** [comment]
I agree, this doesn't seem to be an issue anymore
