### ISSUE TITLE
Spreadsheet: some headers disappear when scrolling

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/spreadsheet#262]
**Originally by @Ansku**

---

Sometimes row/column headers disappear when you scroll the spreadsheet to and fro. This seems to be related to hidden rows/columns, and possibly #17673, although either limited to or at least significantly more common in situations where there are more hidden than frozen rows/columns.

---

 Imported from https://dev.vaadin.com/ issue #18171

**Comment by thinwire** [comment]
I'll be taking a look at this next

**Comment by thinwire** [comment]
Finally fixed. Solution was to force redraw of row and column headers after scroll. Failing that, the entire draw logic needs to be re-thought.
