### ISSUE TITLE
Removing table breaks Spreadsheet

### ISSUE THREAD

**Issue by Peppe** [vaadin/spreadsheet#428]
## Steps to reproduce
1. Go to http://demo.vaadin.com/spreadsheet/
2. Choose some cells
3. Right click on a cell 
4. Choose "Create Table on K4:L9" from context menu
5. RIght click on a cell again
5. Choose "Delete Table on K4:L9" from context menu
6. Try to go to another example in the demo

## Expected behaviour
The table is deleted in 5 and you go to the other example

## Actual behaviour
The table is not deleted on step 5. Nothing happens when you try to go to another example

**Comment by alvarezguille** [comment]
Seems to be related to cc1c2d4
