### ISSUE TITLE
CellValueManager improperly sets cellData.needsMeasure=true for string-valued formulas

### ISSUE THREAD

**Issue by WoozyG** [vaadin/spreadsheet#456]
CellValueManager.createCellDataForCell(Cell)

always sets the shared state CellData field needsMeasure to true for all cells of any type other than plain String.  In Version 1.3.0 it's on line 296.

This is incorrect in the case of formula cell values that return a String.  This can be found by adding this check to the "else if" condition on line 295:

getCachedFormulaResultType()
else if (cell.getCellType() != Cell.CELL_TYPE_STRING || (cell.getCellType() == Cell.CELL_TYPE_FORMULA && cell.getCachedFormulaResultType() != Cell.CELL_TYPE_STRING) )

note the need to check first if it is a formula cell, as getCachedFormulaResultType() throws an IllegalStateException if called when the cell is not a formula.

Also, why can't I set a custom CellValueManager to fix this locally, like I can for other Spreadsheet helper classes?  That's very frustrating.

The result of this bug is that string valued formula cells are truncated in the display, while Excel displays the result text overflowing to adjoining cells if they are empty.  This is a serious display bug for our files, as there are many formula text cells with text that is expected to flow over cells to the right.

**Comment by WoozyG** [comment]
Further, the Spreadsheet class is sloppy in it's use of the valueManager field - some references are via getCellValueManager(), others are direct to the field.

If all references were via the getter, I could simply override the getter and return a wrapped version that fixes this and any other bugs I find, without having to wait on a full Vaadin release cycle.

**Comment by WoozyG** [comment]
One can verify the fix for this by creating a workbook with a formula evaluating to a long text value, making the column narrow, then display in Vaadin Spreadsheet.  Change the cell to the plain text of the formula result and see the difference.

It can be temporarily fixed if anyone else has this issue by adding the following extremely awful and dangerous hack to the constructors of a subclass of Spreadsheet:

```java
try {
	Field field = Spreadsheet.class.getDeclaredField("valueManager");
	field.setAccessible(true);
	
	Field modifiers = Field.class.getDeclaredField("modifiers");
	modifiers.setAccessible(true);
	modifiers.setInt(field, field.getModifiers() & ~ Modifier.FINAL);
	field.set(this, new CellValueManager(this) {
		private static final long serialVersionUID = 1L;
		@Override
		protected CellData createCellDataForCell(Cell cell) {
			CellData data = super.createCellDataForCell(cell);
			data.needsMeasure = ! (cell.getCellTypeEnum() == CellType.STRING || (cell.getCellTypeEnum() == CellType.FORMULA && cell.getCachedFormulaResultTypeEnum() == CellType.STRING) );
			return data;
		}
	});
} catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
	LOG.error("We tried fixing bug #456, but failed.", e);
}
```

**Comment by sblommers** [comment]
Nice find, what I did was copying the CellValueManager.java file into my project and edit directly overriding the source I recognize that is mostly the fastest way to find/fix bugs in this project also the patches can be extracted directly from this source
