### ISSUE TITLE
Spreadsheet-charts class XSSFChartReader.getTitle() is private and converts plot name as chart title to uppercase

### ISSUE THREAD

**Issue by WoozyG** [vaadin/spreadsheet#483]
in fact all methods are private.  I'll need to copy the whole class to override this behavior.  Why in the world would Vaadin assume we didn't mean it when we used mixed case for chart titles?  If we explicitly title the chart, it is left alone, but if we use the default series name, it is converted to uppercase. That's not right.

**Comment by WoozyG** [comment]
Further, the upper-casing is done in the system default Locale, instead of any session/user/UI specific Locale.

**Comment by WoozyG** [comment]
Easiest workaround I've found so far is to create my own subclass of `DefaultChartCreator` and override this method.  Charts must have at least one series, so no bounds check needed.

```
	public Component createChart(XSSFChart chartXml, Spreadsheet spreadsheet) {
		final Chart chart = (Chart) super.createChart(chartXml, spreadsheet);
		final List<Series> series = chart.getConfiguration().getSeries();
		String firstSeriesName = series.size() == 0 ? null : series.get(0).getName();
		// recover from hard-coded private upper-casing.  See Spreadsheet bug #483
		if (firstSeriesName != null && chart.getConfiguration().getTitle().getText().compareToIgnoreCase(firstSeriesName.toUpperCase()) == 0) {
			chart.getConfiguration().getTitle().setText(firstSeriesName);
		}
		return chart;
	}

**Comment by MTzukanov** [comment]
Hi WoozyG,

The development of chart module was added as a requirement from a specific customer, so this specific thing (uppercase) was probably done by their requirements. You are welcome to submit your pull requests.
