### ISSUE TITLE
Charts don't recognize numeric series labels

### ISSUE THREAD

**Issue by WoozyG** [vaadin/spreadsheet#485]
`com.vaadin.addon.spreadsheet.charts.converter.xssfreader.AbstractSeriesReader.getCategoryCellReferences(CTAxDataSource)` checks for string category labels, but not numeric ones.

It needs the same check for `isSetNumRef()` and the same referenced cell logic as for `isSetStrRef()`.

**Comment by WoozyG** [comment]
Adding the check mentioned above works for me if I copy the class to my source and deploy to Tomcat, which explicitly states `WEB-INF/classes/` is checked before `WEB-INF/lib/*.jar` libraries by the web app ClassLoader.

```
        } else if (axisDataSource.isSetNumRef()) {
            String formula = axisDataSource.getNumRef().getF();
            return Utils.getAllReferencedCells(formula, spreadsheet,
                    showDataInHiddenCells);
        }
```

The caller doesn't care what data type the cells are.

See https://tomcat.apache.org/tomcat-8.0-doc/class-loader-howto.html for the Tomcat ClassLoader order specification. 

I don't want to do this long term, though, since it copies a Vaadin class, and I won't notice changes/other bug fixes.  It should be dynamically configurable and non-private so it can be overridden.

We should also work out some better POI interfaces so we don't need the ugly code checking all the different chart types then using reflection to call common methods because they don't share an interface.  As a POI committer, that just irks me.

**Comment by WoozyG** [comment]
Filed POI enhancement request https://bz.apache.org/bugzilla/show_bug.cgi?id=60847 for such a better interface for reading chart series data and configuration.  

If Vaadin has feedback/input on such an enhancement, we can discuss it there.  

Meanwhile, this specific bug would be a nice fix in the next maintenance release.  We use numeric cells for chart labels often (they are year numbers).

**Comment by alvarezguille** [comment]
Hi @WoozyG, thanks for reporting this. Charts API is quite extensive and some of it might not be considered yet.

**Comment by WoozyG** [comment]
Then please address #486 so ProTools users can properly extend and customize their implementations.  The marketing doesn't match the reality yet for charts in Vaadin Spreadsheet.  We are making it a centerpiece of our product, but I'm having to rewrite large portions of the integration, which makes the value add questionable.

**Comment by WoozyG** [comment]
Thanks for the quick fix, with unit test!  I'll keep filing bugs/enhancements as I encounter them, for your team to dispatch and prioritize.  I agree, both Excel charts and HighCharts have enormous feature sets, so deciding which ones to implement in what order is arbitrary and based on customer demand.  So I'll make some demands, and you can tell me where Vaadin will go and where I'm on my own :)

**Comment by sblommers** [comment]
Good work on this one. We also use charting quite extensively but it is still a bit limited. I hacked and slashed in some code as wel to get this going. Would be nice to get this into the product. I am glad more ppl are working on this. High five Alvarez and Greg !

**Comment by alvarezguille** [comment]
Hey @WoozyG and @sblommers, thanks for the feedback on this one!
Without falling into the hated "patches welcome" attitude, all collaboration is welcome. 
Issues are good feedback, but if any of you already knows the cause and/or have a solution please share it, example files are also helpful since it makes it super easy to reproduce and add test to prevent regressions in the future. 
Of course a PR is even better. I think #487 was a good example of how simple a fix and test can be done. We can discuss about how to make PR and reviews easier if needed.
This fix will be released with next maintenance release later this week
