### ISSUE TITLE
Pie chart subtitles aren't shown when data and chart are in different sheets.

### ISSUE THREAD

**Issue by felype87** [vaadin/spreadsheet#594]
Steps to reproduce:

1. Import [Workbook2.xlsx](https://github.com/vaadin/spreadsheet/files/1199973/Workbook2.xlsx).

Observed behavior: Subtitles aren't shown. Open the file with Excel to see them.
Expected behavior: Subtitles Header 1, Header 2 and Header 3 are shown.

**Comment by DiegoCardoso** [comment]
Could you inform which versions of Vaadin and Spreadsheet you are using?
