### ISSUE TITLE
about error java.lang.NoSuchMethodError: Lcom/vaadin/shared/Registration

### ISSUE THREAD

**Issue by shigaHazuki** [vaadin/spreadsheet#597]
I try to use spreadsheet in a vaadin 7.7.5 with spring boot. I installed and compiled the widgetset, I also used my key I get the following error: Java.lang.NoSuchMethodError: com.vaadin.addon.spreadsheet.Spreadsheet.addListener (Ljava/lang/Class; Ljava/lang/Object; Ljava/lang/reflect/Method;) Lcom/vaadin/shared/Registration;

Do you know where this error comes from? It does not seem to be related to the code but rather to the installation.

Thank you, have a nice day

**Comment by Artur-** [comment]
You have a mix of Vaadin 7 and Vaadin 8 in your project

**Comment by shigaHazuki** [comment]
I do not have a version conflict with the vaadin components, is that a conflict with the poi components could be the cause?

**Comment by Artur-** [comment]
You need to use Spreadsheet 1, not 2 with Vaadin 7

**Comment by shigaHazuki** [comment]
I think having the right version of the spreadsheet seen as dependencies are of vaadin are in 7.7.5? Otherwise I will try with 1 version
![capture du 2017-08-18 14-50-04](https://user-images.githubusercontent.com/12912077/29459620-d028f91c-8424-11e7-8f5c-0fcaadadde8d.png)

**Comment by alvarezguille** [comment]
As @Artur- said Spreadsheet 2.0+ is compatible with Vaadin 8.0+ while Spreadsheet 1.0+ should be used for Vaadin 7.4+. 
Can you try using version 1.3.4 or 1.4.0.alpha2?
That should solve the `Java.lang.NoSuchMethodError`
