### ISSUE TITLE
Using arrow keys to leave cell value editor

### ISSUE THREAD

**Issue by ianscriven** [vaadin/spreadsheet#598]
In excel, you can use the arrow keys to leave the cell "editor" and navigate to adjoining cells. For example, if you start typing in cell B2, then press the down arrow, you will leave the editor (saving the value you entered) and select cell B3. Similarly for the up, left & right arrow keys.

I've found two related issues:
#235
#246 

It looks as though, while raised, this was only every partially addressed? Arrow keys do go into the cell-picker mode when entering a formula.

**Comment by vlukashov** [comment]
We aim at releasing a fix for this issue in the next maintenance release of Vaadin Spreadsheet.
