### ISSUE TITLE
No update of expandend region (after ungrouping action)

### ISSUE THREAD

**Issue by kiaruska** [vaadin/spreadsheet#599]
The spreading of a group of columns always produces the updates the cell of the first group with the same level of nesting.

For example, when we click on the second group, the cell "C1" is not updated: 
the value of the cell is "#" instead of "0", because the client wasn't informed about the change of column width.
[ungrouping_cellUpdating.xlsx](https://github.com/vaadin/spreadsheet/files/1242072/ungrouping_cellUpdating.xlsx)

**Comment by vlukashov** [comment]
A fix for this issue will be available in the next maintenance release of Vaadin Spreadsheet (in both branches: 1.4 and 2.1).
