### ISSUE TITLE
NPE in Vaadin Spreadsheet

### ISSUE THREAD

**Issue by taurus227** [vaadin/spreadsheet#603]
If createCell is invoked with a null value, this line gives an NPE:
https://github.com/vaadin/spreadsheet/blob/fd6b95a0e8bf4c13ce91d0e44d7be5b7a16c39f4/vaadin-spreadsheet/src/main/java/com/vaadin/addon/spreadsheet/Spreadsheet.java#L1686

**Comment by vlukashov** [comment]
Hi @taurus227! Thanks for taking the time to report an issue!
We aim at releasing a fix in the next minor version of Vaadin Spreadsheet.
