### ISSUE TITLE
Missing import in 2.1.0.alpha1 Causes problem in OSGi environment

### ISSUE THREAD

**Issue by QNENet** [vaadin/spreadsheet#645]
The spreadsheet jar is an OSGi jar that misses an import.
  org.apache.poi.ss                      
  org.apache.poi.ss.format 
 org.apache.poi.ss.formula <<<<<< needs this              
  org.apache.poi.ss.formula.eval         
  org.apache.poi.ss.formula.ptg          
 
When running in my OSGi project it reports
"java.lang.NoClassDefFoundError: org/apache/poi/ss/formula/FormulaParseException" and I think the missing import is the reason as FormulaParseException is in the org.apache.poi.ss.formula package.

**Comment by chrisnaan** [comment]
We have manually editted the manifest, but it would be nice if this could be fixed.

**Comment by DiegoCardoso** [comment]
Closed by #703
