### ISSUE TITLE
Address bar navigation to cell doesn't scroll enough if column is out of viewport

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/spreadsheet#664]
To reproduce:
* create a new spreadsheet
* type "AY3" in address bar
* "AY3" is selected, but not visible, in my case AV column is the rightmost visible

**Comment by alvarezguille** [comment]
NavigationTest#testEnterSelectionRangeInAddress_outsideOfViewport should be unignored when fixing this

**Comment by jeremystucki** [comment]
The same is true for rows. If I enter `A4000` the correct Cell is selected, but the viewport begins at 4159.
