### ISSUE TITLE
Selecting a value in a dropdown generates a large JSON file (~ 1.6MB)

### ISSUE THREAD

**Issue by kobal007** [vaadin/spreadsheet#713]
I believe this issue is related to a previously closed issue: https://github.com/vaadin/spreadsheet/issues/338

I've included a sample project that replicates the issue. 
[spreadsheet_bug.zip](https://github.com/vaadin/spreadsheet/files/4118396/spreadsheet_bug.zip)

Whenever we change a combobox value the page freezes for about 4-5 minutes while it generates a large json file that is then passed back to the browser for processing. It only happens on a particular sheet in our project and only the first time we go to that particular sheet. After that it seems to work fine until we switch sheets and then go back and have to wait another 4-5 minutes all over again. 

we are using version 3.0.0.alpha1 of the Vaadin Spreadsheet component.

**Comment by kobal007** [comment]
[new_spreadsheet_bug.zip](https://github.com/vaadin/spreadsheet/files/4194847/new_spreadsheet_bug.zip)


included a new version of the sample that is vaadin 8.10.0 only

**Comment by tulioag** [comment]
Seems to be related to the evaluation of the formulas in "O" and "P" columns. 

`=IF(ISNA(INDIRECT("Lists!D"&(MATCH(N10,Lists!C:C,0)))),"",INDIRECT("Lists!D"&(MATCH(N10,Lists!C:C,0))))`

**Comment by kobal007** [comment]
Is this something that can be mitigated somehow? We don't have control of the spreadsheet so we wouldn't be able to remove those formulas.
