### ISSUE TITLE
Formatting changes after editing cell

### ISSUE THREAD

**Issue by thargor6** [vaadin/spreadsheet#723]
Issue found in **Vaadin Spreadsheet for Flow 1.0.0.alpha1**

After editing a cell:
![spreadsheet_edit_1](https://user-images.githubusercontent.com/1161416/150760694-6d3c6932-5bc3-4ec0-8654-f728f4d5d563.png)
the font or font-size seems to be reset to some default one:
![spreadsheet_edit_2](https://user-images.githubusercontent.com/1161416/150760810-1c437d72-f8c6-45f4-8e8d-90336011f49f.png)

**Comment by manolo** [comment]
@thargor6 can you provide an excel  file that we can use for reproducing the issue, so far we couldn't reproduce it.

**Comment by thargor6** [comment]
Hi, I have attached an example
[example_test2.xlsx](https://github.com/vaadin/spreadsheet/files/8349807/example_test2.xlsx)

**Comment by manolo** [comment]
Cannot reproduce in current `flow-port` branch, perhaps because we have introduce some changes. I'll put this issue on hold until we have snapshots so as you can test it.

![formatting-issue](https://user-images.githubusercontent.com/161853/160588814-1a95891a-c00f-4407-8501-86e252175c93.gif)
