### ISSUE TITLE
z-index problems with the spreadsheet widget

### ISSUE THREAD

**Issue by manolo** [vaadin/spreadsheet#757]

**Comment by manolo** [comment]
- app layout menu is covered by the widget
- comment popups are covered by bottom ba
![Screenshot 2022-03-29 at 09 04 06](https://user-images.githubusercontent.com/161853/160553049-0c9cba89-7f34-4051-9d34-4cad6700a705.png)
![Screenshot 2022-03-29 at 09 03 01](https://user-images.githubusercontent.com/161853/160553059-257489fe-0399-4edc-8649-12ad6c3a1e8c.png)
r

**Comment by rolfsmeds** [comment]
That issue with the app-layout drawing getting covered can be fixed by setting `position: relative` and `z-index: 0` on the layout you put in the app-layout, as a workaround until https://github.com/vaadin/web-components/issues/3674 is fixed.
