### ISSUE TITLE
Serialization should not depend on `#` and parsing should not depend on split

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/spreadsheet#759]
Currently [Serializer.java](https://github.com/vaadin/spreadsheet/blob/flow-port/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/Serializer.java) serializes POJOs as `#` separated strings, which breaks when `#` is a valid part of a value. `@` is also used as a magic token.
Serializer should use types allowed in `JsonCodec ` like `JsonValue` for POJOs.

The other part is [Parser.java](https://github.com/vaadin/spreadsheet/blob/flow-port/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/spreadsheet/flowport/gwtexporter/client/Parser.java) which is also fragile. 

A good option is to replace it with [JsonSerializer](https://github.com/vaadin/flow/blob/a4e6649b8f4ba2a6751eb1a39ca4d148b485ab3b/flow-server/src/main/java/com/vaadin/flow/internal/JsonSerializer.java#L67)

Ping @Artur- @Legioth for opinions

**Comment by Artur-** [comment]
Please delete that class

**Comment by Artur-** [comment]
Can't we just use Jackson?

**Comment by manolo** [comment]
@Artur-  Also for the client part ?

**Comment by Artur-** [comment]
Then there is elemental json
