### ISSUE TITLE
Formulas with double quotes don't work

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/spreadsheet#815]
Steps to reproduce:

1. Try to use any formula with double quotes (i.e. `=SUMIF(A1:A10, ">5")`)

![formulas](https://user-images.githubusercontent.com/29372419/163332266-be09e3c6-adef-4e25-a40f-a970bc29b8d5.gif)

Instead of value formula is presented as string.

**Comment by manolo** [comment]
After a bit of investigation, it's a problem on serialisation because quotes are not correctly handled. It should be fixed when #759
